### ISSUE TITLE
Stored XSS

### ISSUE THREAD

**Issue by alvarodh** [h9k/magirc#113]
If you create a channel with your payload, you can see the injection in the 10 top channels:

Version: 1.0.0 
Image:
https://cloud.githubusercontent.com/assets/9592881/5864345/9f7bc3d0-a281-11e4-9994-c1cecd9870bf.png

By @alvarodh5 (twitter)

**Comment by h9k** [comment]
Thanks for reporting and sorry for the slow response.
I believe the problem to be fixed now, I also fixed several similar issues and potential issues I could find.
