### ISSUE TITLE
MagIRC checks in the modes' datas to know if the channel can be displayed

### ISSUE THREAD

**Issue by Zoddo** [h9k/magirc#116]
Exemple: In UnrealIRCd, the mode `+f` adds protections against the flood.  
If I set `+f [2c#C10,30j#R3,2k,100m#M5,4n#N5,30t#b]:60`, the character `k` is present in the channel modes and the channel cannot be displayed.

The responsible is [this condition](https://github.com/h9k/magirc/blob/da0754ab6aac6a8d7c9d2c21e6daf4f13e4418e6/lib/magirc/services/Anope.class.php#L775).

PS : Sorry for my bad english

**Comment by h9k** [comment]
Thanks for reporting and for fixing :)
