### ISSUE TITLE
Add support for atheme (or forks of atheme)

### ISSUE THREAD

**Issue by k0nsl** [h9k/magirc#120]
Any plans to add support for atheme based services or forks of that project?

**Comment by h9k** [comment]
Not at this time. I am not familiar with the Atheme landscape. Does Atheme have a similar statserv/chanstats service like Denora/Anope2?

**Comment by Sheogorath-SI** [comment]
Nope their stats are a bit pointless for magirc... they even don't have SQL support iirc

**Comment by h9k** [comment]
Ok so we can close this issue for now.
I guess it would be possible to code a StatServ module for Atheme, but someone has to do it :)
