### ISSUE TITLE
use correct ircs urls

### ISSUE THREAD

**Issue by Sheogorath-SI** [h9k/magirc#121]
currently `irc://hostname:+port/channel` is used this is not a valid URL type.

`ircs://hostname:port/channel` should be used instead

**Comment by Sheogorath-SI** [comment]
There are still some in server views and in channel views

**Comment by h9k** [comment]
They all use the same javascript so it should be fine everywhere.

**Comment by Sheogorath-SI** [comment]
Ehh... no? I mean the non-JS parts.
https://github.com/h9k/magirc/blob/master/theme/default/tpl/server_list.tpl#L5 
https://github.com/h9k/magirc/blob/master/theme/default/tpl/channel_status.tpl#L23

and my more?

**Comment by h9k** [comment]
oops, forgot about those
