### ISSUE TITLE
menu update function does not trigger

### ISSUE THREAD

**Issue by Sheogorath-SI** [h9k/magirc#122]
In my instance of magirc the update for channel links seems not triggering:
https://github.com/h9k/magirc/blob/master/js/magirc.js#L183-L196

tried to fix it but didn't found the right point :/

currently it always refer to baseurl/# (for all selectable entries)

**Comment by h9k** [comment]
Please update to the latest version from github and let me know how it goes.
If you still have problems, please tell me which web browser you are using.

**Comment by Sheogorath-SI** [comment]
Nope still doesn't work I use Firefox 44.0b on Windows 10.

url: https://stats.madirc.net/

**Comment by h9k** [comment]
Dude, you manipulated magirc.js and added altert('called'); which is misspelled.
Please revert to the original magirc.js and see if it works then.

**Comment by Sheogorath-SI** [comment]
yes, but that manipulation was made after testing for debugging (and yes, it's wrong) but the funny point is it doesn't throw an error to console means no call... means it's not trigger which is the bug I reported

**Comment by h9k** [comment]
hmmm odd, works for me in ff 43, maybe it's a firefox 44 problem

**Comment by Sheogorath-SI** [comment]
Sorry I just misunderstood the whole system >.> it triggers on click to the button I thougt about it should trigger on open the menu.
