### ISSUE TITLE
Display table on page not in /stats

### ISSUE THREAD

**Issue by ghost** [h9k/magirc#127]
@h9k Hi, please can you help me with something?

What is best/simplest method to get this table generated on another page on our site?

![capture](https://cloud.githubusercontent.com/assets/16916976/14278220/72217bc2-fb1e-11e5-9f25-559c3a7fc031.PNG)

Do we include `magirc.min.js`, then what?

Thanks!

**Comment by h9k** [comment]
The best way is to use the REST service and call if with jQuery for example, then process the results.
Please refer to the documentation on https://github.com/h9k/magirc/blob/master/doc/REST.md
MagIRC uses DataTables from datatables.org to render the table, but you can do whatever you like.

**Comment by cehib** [comment]
@h9k Can you give me some advise on how to be able to use the MagIRC JavaScript functions on our front site (not /stats)?

Example:

```
    var table3 = $("#tbl_topusers").DataTable({
        "processing": false,
        "searching": false,
        "info": false,
        "lengthChange": false,
        "paging": false,
        "ordering": false,
        "ajax": "/stats/rest/service.php/users/top/5?format=datatables",
        "columns": [{
            "data": "uname",
            "render": function(data, type, row) {
                return getUserStatus(row) + ' ' + getCountryFlag(row) + ' ' + escapeTags(data) + getUserExtra(row);
            }
        }, {
            "data": "lines"
        }]
    });
```

Without the getUserStatus etc. this table loads data fine, but with it it doesn't work. So I included `magirc.js` but that doesn't help either. What am I missing?

**Comment by h9k** [comment]
i dunno, maybe just copy those methods from magirc.js into a separate file

**Comment by cehib** [comment]
@h9k hmm, still no luck on this. Does the `magirc.js` file rely on being in `/stats` or can it be used anywhere? Do I need to change something in that file if it's not in `/stats`?

**Comment by h9k** [comment]
You just need to load jQuery and DataTables, then the snippet you posted above should work.
