### ISSUE TITLE
blank page in /admin

### ISSUE THREAD

**Issue by Lumiahna** [h9k/magirc#128]
Hello, 
I installed Magic but I've a blank admin page, I can't login as Admin.
os: debian 8
web server: nginx
http://stat.2fy.eu/admin
Cheers,

**Comment by h9k** [comment]
Please update to the latest git version and try again.

**Comment by Lumiahna** [comment]
Hello, 
thx for your answer, I did it but when I hit login button nothing happened.

**Comment by h9k** [comment]
yeah it seems more fixing is needed... will look at it this weekend

**Comment by h9k** [comment]
I fixed the bug with the users currently in channel, and hopefully also the admin pages problem.
Please update to the latest git version. Magirc will force you to run the setup again to update the database. Also, please delete the subfolders present in the tmp directory to refresh templates.

**Comment by Lumiahna** [comment]
Awesome,
It works (:
Thank you for your time :D <3
