### ISSUE TITLE
Twig_Environment::assign() error during setup

### ISSUE THREAD

**Issue by sgermain06** [h9k/magirc#131]
Fatal error: Uncaught Error: Call to undefined method Twig_Environment::assign() in /var/www/magirc/setup/lib/Setup.class.php:119 Stack trace: #0 /var/www/magirc/setup/inc/step2.php(6): Setup->saveConfig() #1 /var/www/magirc/setup/index.php(39): include('/var/www/magirc...') #2 {main} thrown in /var/www/magirc/setup/lib/Setup.class.php on line 119

**Comment by h9k** [comment]
Sorry, cannot reproduce.
Maybe running a composer update will solve the problem?

**Comment by h9k** [comment]
Ah, got it... will fix. Sorry for taking so long to handle this!
