### ISSUE TITLE
Some options not showing on the stats page

### ISSUE THREAD

**Issue by TheMythPT** [h9k/magirc#132]
Some data is not appearing on main stats page, like servers (not the ulined, as that i've set them to hidden).
Here's my anope tables inside anope database:
![anope_tables](https://cloud.githubusercontent.com/assets/25697531/23589469/255702d2-01ce-11e7-8c46-e49d3c0e2bc9.png)

And here's the main page stats (no servers shown, and i have 3 servers, and services (set to not show)):
![main_stats_page](https://cloud.githubusercontent.com/assets/25697531/23589488/57ef7fee-01ce-11e7-8ba2-f09b23fc8f35.png)

If of any help, i'm running UnrealIRCd 4.0.11 & Anope 2.0.6-git.

Any ideas?

**Comment by h9k** [comment]
You seem to be missing some tables like anope_currentusage and anope_maxusage.
Are you sure you enabled the required modules? Those would be m_mysql, m_chanstats and irc2sql. Probably you are missing the latter.

**Comment by TheMythPT** [comment]
i've tried a quick fresh install from anope linked it to a testnet and the tables you pointed arent created by anope.. any clues?

best regards

**Comment by h9k** [comment]
Anope should create those tables automatically, but I'm afraid I cannot help you. I am not that familiar with Anope as I have not configured one in years, so maybe you should head over to the Anope support team and ask them what could be wrong.

**Comment by TheMythPT** [comment]
well, i'll see what o can do. or maybe those tables moved to some other place. i'll check with anope devs and then i'll update you with details.

**Comment by TheMythPT** [comment]
just enlight me what should be in those tables: anope_currentusage and anope_maxusage, so i can ask the devs where i can find inside anope db something that does the same

**Comment by h9k** [comment]
Just a quick update, the tables you are missing are actually from MagIRC, so nothing to bother Anope support about. Sorry about that.
You will find the statements in setup/sql/anope.sql, also please refer to the README.md for setting up the Anope database for MagIRC.

**Comment by TheMythPT** [comment]
well, i've tried, but i cant really understand that.. :x
isnt possible to do a quick patch?
thanks.

**Comment by TheMythPT** [comment]
well, its done, ive executed the anope.sql against the table.. only countries not showing, but i guess that's because of my network is set to 'dont-reaolve' on the ircd.. i guess this means thread closed. :)

**Comment by TheMythPT** [comment]
Thanks for all the help. I'm wainting for the next version ;)
Keep up the good job!

Best regards
