### ISSUE TITLE
Unable to get rewrite to work on nginx using the given example.

### ISSUE THREAD

**Issue by DeadSix27** [h9k/magirc#133]
The regex of the example seems to not work (anymore).

Original one:
`fastcgi_split_path_info ^(.+\.php)(/.+)$;`
Replaced it with:
`fastcgi_split_path_info ^(.+\.php)([\:\/A-z0-9]+)$;`

Not a regex expert, but should be safe(r than the original) I think.

**Comment by h9k** [comment]
Thanks, will update the README with your fix
