### ISSUE TITLE
Language not appearing on the stats page

### ISSUE THREAD

**Issue by TheMythPT** [h9k/magirc#135]
I've uplloaded the portuguese lang file to the locale folder, i've restarted web server but language isnt appearing on the language menu.. what are the steps to follow?

**Comment by h9k** [comment]
no idea, maybe empty the tmp folder. i merged your request and it worked immediatelly for me

**Comment by TheMythPT** [comment]
it appeared, but dont translate the page.. weird tho.. i'll try to reinstall magirc

**Comment by TheMythPT** [comment]
i've reinstalled it, but still no translation.. does your pages appears translated?

**Comment by TheMythPT** [comment]
founded the problem.. the filenames were as pt_PT.po and pt_PT.mo and should be messages.mo and messages.po

**Comment by h9k** [comment]
Yeah it does not translate on my test windows cause i don't have the portuguese locale installed.
Thanks for pointing out, I renamed those files in the repo ;)
