### ISSUE TITLE
Servers displaying as offline; channels not populating; Admin panel showing beta status.

### ISSUE THREAD

**Issue by daemhan** [h9k/magirc#136]
Hello,

We did a fresh installation of MagIRC yesterday, and have run into a few issues:

Servers showing offline:
Currently displaying all of our servers as offline, but they are all online. The database is showing all of the servers as offline as well for some reason -- this could be an Anope issue, not a Mag issue, The main page is also showing 0, however, channel numbers and current users are pretty much on par with /lusers
![image](https://cloud.githubusercontent.com/assets/9834590/25069782/21b30bb4-2251-11e7-8217-5c93d7f6b372.png)
![image](https://cloud.githubusercontent.com/assets/9834590/25069783/2b400858-2251-11e7-8698-dde92480f4a1.png)

Channels not populating:
![image](https://cloud.githubusercontent.com/assets/9834590/25069767/b0e7bcb8-2250-11e7-97af-b19a3c0dc3c4.png)
It has been sitting like that for nearly 24 hours. Users was doing the same thing, but that eventually sorted itself out.

Admin panel is showing this:
![image](https://cloud.githubusercontent.com/assets/9834590/25069772/cfc85ebc-2250-11e7-9207-c56e82b029b8.png)
According to the release history on the news page, this is not a beta release? This is also not a huge issue, just a curiosity.

Any help would be appreciated!

**Comment by h9k** [comment]
Please specify if you are running Anope or Denora, and which IRCd, thanks!

**Comment by daemhan** [comment]
Oops! Sorry about that. Tired me was tired. We're using Anope 2.0.5 and InsIRCd 2.0.23.

**Comment by h9k** [comment]
Would you mind sending me the URL to your install as a private message, so I can have a look?

**Comment by daemhan** [comment]
I don't actually see a way to send a private message via GitHub. Our
install is password protected, and I created a login for you, but would
rather not post that info out in the open.

**Comment by h9k** [comment]
Sorry about that, I thought that would be an obvious feature. Please send the info to hal9000 at magirc dot org.

**Comment by h9k** [comment]
I got your details, thanks.
What PHP version are you running?

**Comment by daemhan** [comment]
We are using: PHP 7.0.15-0ubuntu0.16.04.4

**Comment by h9k** [comment]
I had a look at the problems and did some research.
Please do this, if you have root on the server:
`sudo apt-get install php7.0-xml`
then restart Apache and let me know if it helps.

**Comment by daemhan** [comment]
I'll do that and give it a half a day/full day. I didn't even think about
XML. There had been a few other things missing with the upgrade or paths
wrong that got fixed [the install was much more broken before]. Thank you.
Will see if this works!

**Comment by daemhan** [comment]
In the two minutes it took to install the XML extension, the loading issues
are completely solved. Still no servers reflected as being online, but I
will update after 12-24 hours whether they are reporting properly now or
no. Thanks!

**Comment by h9k** [comment]
Good to hear. Yeah, at some point the PHP ubuntu packages split some stuff from the base packages, and the utf8_decode function for example was moved to php-xml, for whatever reason. I will update the documentation of magirc.
The info about the beta status in the admin panel is a mistake, I will remove that in the next commit.
About the issue that servers are being shown as offline, this information is taken directly from the anope server table. Can you please check what your anope_server table contains in the online column?

**Comment by daemhan** [comment]
Interesting.

The anope_server table was showing everything as offline. Removed the
table, table reformed, waiting for re-population, but I have no idea where
it pulls that information from, so not sure how to nudge it a bit to update
it.

**Comment by daemhan** [comment]
And now I have no servers, no client history, no opers showing, and no
countries showing.

anope_server still hasn't populated anything, I can't figure out where it's
pulling clients from, opers are reflected accurately in various places, and
countries are also populated.

Perplexing.

**Comment by h9k** [comment]
Try to restart Anope and check if the Anope logs show any hint. This seems to be an Anope problem.

**Comment by daemhan** [comment]
Evidently, if you restart Anope 3 times in a row, it knows to properly
update databases. Like clicking your heels three times brings you home to
Kansas.

I restarted servives and checked the logs. Logs showed all the servers
linking properly, database connection happening and databaeses loading
properly. Tables still not loading in Mag, despite them all having data but
for the anope_server table. Two more restarts, and on the third it finally
re-populated the servers table and is now reporting the rest of the items
just fine.

I hadn't thought to restart it again, because I'd already restarted and
reloaded several times before today, but after you provided the XML
information in an attempt to force the servers database to populate. Thanks
for your help! Mag is now reporting all of the things.
