### ISSUE TITLE
Peak info not displaying

### ISSUE THREAD

**Issue by TheMythPT** [h9k/magirc#140]
I had a few problems and I've reinstalled the vps OS.
I've done a fresh install of MagIRC but somehow the peak info isn't being displayed, as it can be seen in the attached image.
Any advise will be good.
![screenshot_2017-05-11-11-52-08](https://cloud.githubusercontent.com/assets/25697531/25943723/1f847838-3641-11e7-880d-007581c66cd5.png)

**Comment by TheMythPT** [comment]
Problem solved. I've forgotten to execute the sql file related to Anope.
All working properly now.
Keep up the good work!
Case closed!

**Comment by TheMythPT** [comment]
I'm reopening this because even after run the anope.sql file, the pek info is not displayed and not even language changing properly on the new vps.. its a KVM server running Linux 16.04.2
Any ideas?

**Comment by TheMythPT** [comment]
Okay, after carefully reading all the steps, i've noticed that i've failed the following:
Note that you need the MySQL event_scheduler set to ON in the MySQL server. If you have enough rights, you can turn it on via SET GLOBAL event_scheduler = ON;
After accessing mysql as root via command line and after typed the command, all info is now displaying properly.
Hope this can help others in same situation.
Issue re-closed.

**Comment by h9k** [comment]
Thanks for sharing this information!
