### ISSUE TITLE
Few features

### ISSUE THREAD

**Issue by TheMythPT** [h9k/magirc#142]
1. Since i have enabled chanstats per default upon nick registration, i'd like to know if there is a way to block a specific user from appering into stats page.
2. Per default the way of viewing stats should be by Words and that should be the first column and Letters the second one. Is there a way to change it?

**Comment by h9k** [comment]
1. nope, not yet
2. you could change it in the templates, however I will consider to implement your suggestion since it makes sense

**Comment by TheMythPT** [comment]
Yes that would be great. I'd like also to have some advise on the issue #140 because this time i dont know whats happening..
I've migrated all for a new VPS and somehow, MagIRC is not displaying the peak stats..
I've folloe the instructions to install with composer, teh database connection works well, and i even have renamed htaccess.txt to .htaccess..

I've also added this to apach2.conf:<Directory /home/magirc/public_html/magirc>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

Any ideas are appreciated

**Comment by h9k** [comment]
I think the peak stats are being generated by a mysql task, as per README.md file you should edit and run setup/sql/anope.sql and make sure the db user has proper permissions to run the task
