### ISSUE TITLE
Denora

### ISSUE THREAD

**Issue by Indjov** [h9k/magirc#143]
How can i use MagIRC ?  Only with the Anope Services ? Just becouse we try with denora but in make install we get a error.
Any suggestion.

**Comment by h9k** [comment]
MagIRC supports both Anope and Denora. However, Denora is not being actively supported/developed anymore... so no idea what could be your problem...

**Comment by Indjov** [comment]
That it`s the error when i try to run make install

/usr/bin/install stats /stats
/usr/bin/install: cannot remove ‘/stats’: Permission denied
Makefile:125: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/denora/denora/src'
Makefile:171: recipe for target 'install' failed
make: *** [install] Error 2

Any idea ?

**Comment by h9k** [comment]
sorry, this is a denora-related issue, cannot help you with that... you can try the denora forums, but keep in mind that denora is no longer actively maintained
