### ISSUE TITLE
Error nginx with magirc

### ISSUE THREAD

**Issue by amoutai** [h9k/magirc#147]
Hi,

I have a loop error in my nginx errors with magirc and I do not know where it came from

> 2018/01/23 00:12:58 [error] 31585#0: *21115898 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Magirc::jsonOutput() in /var/www/magirc/lib/magirc/Magirc.class.php on line 266" while reading response header from upstream, client: 46.105.45.44, server: magirc.domaine.fr, request: "GET /rest/service.php/channels/%23accueil/users HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "magirc.domaine.fr"

Thank you for future help

**Comment by h9k** [comment]
What version of magirc are you running?

**Comment by amoutai** [comment]
MagIRC v1.5.0-anope

Url : https://magirc.chaat.fr

**Comment by h9k** [comment]
Thanks. So Magirc appears to work fine, but you see these errors in the log, did I understand correctly?

**Comment by amoutai** [comment]
yes I see it in the logs and the "max" does not work it remains at 0

**Comment by h9k** [comment]
The error you were having should have been fixed.
As for the max remaining 0, your Anope SQL probably was not set fully set up, please see the section "Anope Configuration" in the Readme. Probably your MySQL scheduler is turned off or something.

**Comment by amoutai** [comment]
hi,

I have an error since I made the update :

2018/02/09 15:19:15 [error] 32175#0: *223 FastCGI sent in stderr: "PHP message: PHP Fatal error: Class 'Gettext\Translator' not found in /var/www/magirc/lib/magirc/Magirc.class.php on line 19" while reading response header from upstream, client: 82.227.247.188, server: magirc.site.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "magirc.site.fr"

**Comment by h9k** [comment]
You should run composer update and bower update after a git pull

**Comment by amoutai** [comment]
I have an error console :

> jquery.min.js:2 Uncaught TypeError: Cannot read property 'date' of undefined
    at HTMLDocument.<anonymous> (magirc.js:2)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)

I do not know why the max stays at 0 , everything else seems to work perfectly : https://magirc.chaat.fr

My bdd : http://i.imgur.com/Z2cf4P6.png

**Comment by h9k** [comment]
On which page do you see that error?
About max users... again, your MySQL events are not working.

**Comment by amoutai** [comment]
I see this error on the page : https://magirc.chaat.fr

about max users, it's ok , I had to activate event-scheduler , thanks :)

**Comment by amoutai** [comment]
Sorry in fact I do not have an error, I had to empty my cache , thanks you.

It is possible to ignore users as for the channel ignorance for the stats?

**Comment by h9k** [comment]
the user should have to do
`/ns set chanstats off`
