### ISSUE TITLE
Cannot install on latest Debian/PHP

### ISSUE THREAD

**Issue by anaely** [h9k/magirc#150]
Cannot install on latest Debian/PHP using latest MagIRC and Denora

Installed packages -

php
php-gettext
php-mysql
php-xml

When I visit /setup I receive

Please run the `composer install` or `php composer.phar install` command. See README for more information

But this system does not have composer or bower.

Please advise steps to complete install?

**Comment by h9k** [comment]
Sorry about that, looks like our download archives did not include the vendor libraries.
Please redownload again from https://www.magirc.org/download/ and you should be good to go.
