### ISSUE TITLE
I'm looking for the beautiful MagIRC theme - it can't be found

### ISSUE THREAD

**Issue by Madriix** [h9k/magirc#154]
Hi, how can I get the same MagIRC theme as simosnap.org ? I have been looking for it for 1 year, it is too good. thank you in advance

**Comment by Octala** [comment]
Hello, are you talking about this theme: https://www.simosnap.org/ also visible here: https://network.chaat.fr/? I'm also looking for it without success :/

**Comment by h9k** [comment]
I am not aware of any third party magirc themes being available to download anywhere :(
Just ask the guys from those networks, maybe they are willing to provide that in some form. That would certainly be cool.
